### ISSUE TITLE
按着修改没有推送，不知道哪里错了

### ISSUE THREAD

**Issue by linep47** [Peach-Coding/rssbot#7]
请问fork完，按着教程修改就行了吗
![25x](https://user-images.githubusercontent.com/99251630/216555992-01e27da5-45ba-4a53-b724-a8663ab86eb1.png)

**Comment by LeetaoGoooo** [comment]
不好意思～这个配置文件里，我把执行分支改成了 dev 分支，你需要将 

https://github.com/LeetaoGoooo/dingding-rssbot/blob/e38bc74393b1f30c20752b1f2d5a7c49f714319b/.github/workflows/rssbot.yml#L14-L15

这两行代码删掉，然后将

https://github.com/LeetaoGoooo/dingding-rssbot/blob/e38bc74393b1f30c20752b1f2d5a7c49f714319b/.github/workflows/rssbot.yml#L40

改成 `main`，然后就可以了

**Comment by linep47** [comment]
十分感谢您的解答，这个项目对于我这种喜欢订阅rss的人来说非常实用
________________________________
发件人: leetao ***@***.***>
发送时间: 2023年2月3日 17:29
收件人: LeetaoGoooo/dingding-rssbot ***@***.***>
抄送: lineporte ***@***.***>; Author ***@***.***>
主题: Re: [LeetaoGoooo/dingding-rssbot] 按着修改没有推送，不知道哪里错了 (Issue #7)


不好意思～这个配置文件里，我把执行分支改成了 dev 分支，你需要将

https://github.com/LeetaoGoooo/dingding-rssbot/blob/e38bc74393b1f30c20752b1f2d5a7c49f714319b/.github/workflows/rssbot.yml#L14-L15

这两行代码删掉，然后将

https://github.com/LeetaoGoooo/dingding-rssbot/blob/e38bc74393b1f30c20752b1f2d5a7c49f714319b/.github/workflows/rssbot.yml#L40

改成 main，然后就可以了

―

**Comment by LeetaoGoooo** [comment]
@linep47 很开心项目能帮到你，我看了一下你的代码，你不要把那些 token 放到 rssbot.yml 中，点击项目的 settings（最右边的 tab）

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/10162120/216604817-28bcdf87-5eff-4362-9c95-968de1913bde.png">

添加 `WEBHOOK, SECRET, TOKEN ` 三个变量

**Comment by linep47** [comment]
好的 谢谢你 难怪我觉得都放出来感觉不太对 祝大大顺顺心心，万事如意
________________________________
发件人: leetao ***@***.***>
发送时间: 2023年2月3日 20:34
收件人: LeetaoGoooo/dingding-rssbot ***@***.***>
抄送: lineporte ***@***.***>; Mention ***@***.***>
主题: Re: [LeetaoGoooo/dingding-rssbot] 按着修改没有推送，不知道哪里错了 (Issue #7)


@linep47<https://github.com/linep47> 很开心项目能帮到你，我看了一下你的代码，你不要把那些 token 放到 rssbot.yml 中，点击项目的 settings（最右边的 tab）

[image]<https://user-images.githubusercontent.com/10162120/216604817-28bcdf87-5eff-4362-9c95-968de1913bde.png>

―
